/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tms;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ravi
 */
public class home extends javax.swing.JFrame {
    int user_id = 0;
    int texi_no=0;
    /**

     * Creates new form home
     */
    public home(int id) {
        
        initComponents();
        user_id =  id;
        jp_booking.setVisible(false);
        jp_paying.setVisible(false);
        jp_cancel.setVisible(false);
        jp_txt.setVisible(true);
    }

    private home() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_tms = new javax.swing.JPanel();
        lbl_booking = new javax.swing.JLabel();
        lbl_payment = new javax.swing.JLabel();
        lbl_cancel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jp_booking = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txt_purpose = new javax.swing.JTextField();
        cmd_done = new javax.swing.JButton();
        cmd_cancel = new javax.swing.JButton();
        jp_paying = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_payment = new javax.swing.JTextField();
        cmd_yesPayment = new javax.swing.JButton();
        cmd_noPayment = new javax.swing.JButton();
        box_paymentMode = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_texiNo = new javax.swing.JTextField();
        jp_cancel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_texiNumber = new javax.swing.JTextField();
        cmd_yesCancel = new javax.swing.JButton();
        cmd_noCancel = new javax.swing.JButton();
        cmd_logout = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jp_txt = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_tms.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Travel Managment System", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Abyssinica SIL", 3, 18), new java.awt.Color(213, 17, 17))); // NOI18N

        lbl_booking.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lbl_booking.setForeground(new java.awt.Color(66, 82, 63));
        lbl_booking.setText("       Booking");
        lbl_booking.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(98, 27, 151), new java.awt.Color(233, 62, 141)));
        lbl_booking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_bookingMouseClicked(evt);
            }
        });

        lbl_payment.setBackground(new java.awt.Color(227, 165, 234));
        lbl_payment.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lbl_payment.setForeground(new java.awt.Color(197, 148, 148));
        lbl_payment.setText("       Payment");
        lbl_payment.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(37, 149, 167), new java.awt.Color(120, 227, 199)));
        lbl_payment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_paymentMouseClicked(evt);
            }
        });

        lbl_cancel.setBackground(new java.awt.Color(143, 160, 112));
        lbl_cancel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbl_cancel.setForeground(new java.awt.Color(177, 72, 30));
        lbl_cancel.setText("      Cancellation");
        lbl_cancel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(238, 160, 160), new java.awt.Color(107, 74, 74)));
        lbl_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cancelMouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(32, 147, 127));
        jLabel10.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(37, 51, 220));
        jLabel10.setText("Call 24 hours (prefix city code) 11 11 11  11");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(213, 136, 136), new java.awt.Color(188, 153, 153)));

        javax.swing.GroupLayout jp_tmsLayout = new javax.swing.GroupLayout(jp_tms);
        jp_tms.setLayout(jp_tmsLayout);
        jp_tmsLayout.setHorizontalGroup(
            jp_tmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_tmsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbl_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(lbl_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(lbl_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_tmsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jp_tmsLayout.setVerticalGroup(
            jp_tmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_tmsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jp_tmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jp_booking.setBackground(new java.awt.Color(145, 237, 206));
        jp_booking.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Texi Booking", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Abyssinica SIL", 2, 14), new java.awt.Color(33, 18, 154))); // NOI18N
        jp_booking.setForeground(new java.awt.Color(158, 193, 96));
        jp_booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_bookingMouseClicked(evt);
            }
        });

        jLabel2.setText("   Name");

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        jLabel3.setText("  Phone");

        jLabel4.setText("Address");

        txt_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneActionPerformed(evt);
            }
        });

        txt_address.setColumns(20);
        txt_address.setRows(5);
        jScrollPane1.setViewportView(txt_address);

        jLabel5.setText("  Purpose");

        txt_purpose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_purposeActionPerformed(evt);
            }
        });

        cmd_done.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cmd_done.setForeground(new java.awt.Color(11, 189, 35));
        cmd_done.setText("Done");
        cmd_done.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmd_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_doneActionPerformed(evt);
            }
        });

        cmd_cancel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cmd_cancel.setForeground(new java.awt.Color(210, 28, 28));
        cmd_cancel.setText("Cancel");
        cmd_cancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(180, 13, 221), new java.awt.Color(159, 27, 27), new java.awt.Color(19, 137, 77), new java.awt.Color(204, 104, 104)));
        cmd_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_bookingLayout = new javax.swing.GroupLayout(jp_booking);
        jp_booking.setLayout(jp_bookingLayout);
        jp_bookingLayout.setHorizontalGroup(
            jp_bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_bookingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jp_bookingLayout.createSequentialGroup()
                        .addGroup(jp_bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_bookingLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_bookingLayout.createSequentialGroup()
                        .addComponent(txt_purpose)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_bookingLayout.createSequentialGroup()
                        .addGroup(jp_bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_phone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_name))
                        .addContainerGap())))
            .addGroup(jp_bookingLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(cmd_done, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(cmd_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_bookingLayout.setVerticalGroup(
            jp_bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_bookingLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jp_bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jp_bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_bookingLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_bookingLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_purpose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jp_bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_done)
                    .addComponent(cmd_cancel))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jp_paying.setBackground(new java.awt.Color(33, 222, 222));
        jp_paying.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Abyssinica SIL", 2, 14))); // NOI18N
        jp_paying.setForeground(new java.awt.Color(228, 150, 150));
        jp_paying.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jp_paying.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_payingMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(102, 22, 22));
        jLabel1.setText("     Amount");

        cmd_yesPayment.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cmd_yesPayment.setForeground(new java.awt.Color(64, 220, 39));
        cmd_yesPayment.setText("Yes");
        cmd_yesPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_yesPaymentActionPerformed(evt);
            }
        });

        cmd_noPayment.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cmd_noPayment.setForeground(new java.awt.Color(194, 29, 29));
        cmd_noPayment.setText("Cancel");
        cmd_noPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_noPaymentActionPerformed(evt);
            }
        });

        box_paymentMode.setForeground(new java.awt.Color(226, 115, 115));
        box_paymentMode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Credit Card", "Cheque", "Internet Banking" }));
        box_paymentMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_paymentModeActionPerformed(evt);
            }
        });

        jLabel6.setText("Payment Mode ");

        jLabel8.setText("Texi Number");

        txt_texiNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_texiNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_payingLayout = new javax.swing.GroupLayout(jp_paying);
        jp_paying.setLayout(jp_payingLayout);
        jp_payingLayout.setHorizontalGroup(
            jp_payingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_payingLayout.createSequentialGroup()
                .addGroup(jp_payingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_payingLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(cmd_yesPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmd_noPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_payingLayout.createSequentialGroup()
                        .addGroup(jp_payingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp_payingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jp_payingLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jp_payingLayout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_payingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(box_paymentMode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_payment)
                            .addComponent(txt_texiNo))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jp_payingLayout.setVerticalGroup(
            jp_payingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_payingLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jp_payingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_texiNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_payingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box_paymentMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jp_payingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_payingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_noPayment)
                    .addComponent(cmd_yesPayment))
                .addGap(39, 39, 39))
        );

        jp_cancel.setBackground(new java.awt.Color(172, 111, 120));
        jp_cancel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cancellation", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Abyssinica SIL", 2, 14), new java.awt.Color(33, 11, 33))); // NOI18N
        jp_cancel.setForeground(new java.awt.Color(184, 31, 160));

        jLabel7.setText("Texi  Number");

        txt_texiNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_texiNumberActionPerformed(evt);
            }
        });

        cmd_yesCancel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cmd_yesCancel.setForeground(new java.awt.Color(36, 143, 191));
        cmd_yesCancel.setText("YES");
        cmd_yesCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_yesCancelActionPerformed(evt);
            }
        });

        cmd_noCancel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cmd_noCancel.setForeground(new java.awt.Color(154, 31, 31));
        cmd_noCancel.setText("Cancel");
        cmd_noCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmd_noCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_noCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_cancelLayout = new javax.swing.GroupLayout(jp_cancel);
        jp_cancel.setLayout(jp_cancelLayout);
        jp_cancelLayout.setHorizontalGroup(
            jp_cancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cancelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jp_cancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_cancelLayout.createSequentialGroup()
                        .addComponent(cmd_yesCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(cmd_noCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_cancelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_texiNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jp_cancelLayout.setVerticalGroup(
            jp_cancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cancelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jp_cancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_texiNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jp_cancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_yesCancel)
                    .addComponent(cmd_noCancel))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        cmd_logout.setBackground(new java.awt.Color(170, 34, 8));
        cmd_logout.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cmd_logout.setForeground(new java.awt.Color(152, 188, 80));
        cmd_logout.setText("Logout");
        cmd_logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(107, 35, 251), null, null));
        cmd_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmd_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_logoutActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(93, 33, 72));
        jLabel9.setText("  Welcome!!!!!!");

        jp_txt.setBackground(new java.awt.Color(227, 188, 191));
        jp_txt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp_txt.setForeground(new java.awt.Color(48, 93, 105));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(142, 30, 62));
        jTextArea1.setRows(5);
        jTextArea1.setText("TMS offers cabs in Hyderabad  along with full day car rentals &  half day   car \nrentals in Hyderabad at lowest rates. TMS provides car rentals for all kinds \n of city taxi needs, railway station transfers,  airport transfers and  people \ncan opt from the best car rental deals and hire cheap taxi services  in\n Hyderabad for travelling.");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jp_txtLayout = new javax.swing.GroupLayout(jp_txt);
        jp_txt.setLayout(jp_txtLayout);
        jp_txtLayout.setHorizontalGroup(
            jp_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_txtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jp_txtLayout.setVerticalGroup(
            jp_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_txtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jp_tms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jp_booking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jp_paying, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jp_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jp_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(345, 345, 345)
                        .addComponent(cmd_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmd_logout)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_tms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jp_cancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jp_paying, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jp_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jp_booking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_bookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_bookingMouseClicked
        // TODO add your handling code here:
        jp_paying.setVisible(false);
        jp_cancel.setVisible(false);
        jp_txt.setVisible(false);
        jp_booking.setVisible(true);        
    }//GEN-LAST:event_lbl_bookingMouseClicked

    private void lbl_paymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_paymentMouseClicked
        // TODO add your handling code here:
        jp_booking.setVisible(false);
        jp_cancel.setVisible(false);
        jp_txt.setVisible(false);
        jp_paying.setVisible(true);
    }//GEN-LAST:event_lbl_paymentMouseClicked

    private void jp_bookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_bookingMouseClicked
        // TODO add your handling code here:
        //jp_paying.setVisible(false);
       // jp_booking.setVisible(true);
    }//GEN-LAST:event_jp_bookingMouseClicked

    private void jp_payingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_payingMouseClicked
        // TODO add your handling code here:
        
        //jp_booking.setVisible(false);
        //jp_paying.setVisible(true);
    }//GEN-LAST:event_jp_payingMouseClicked

    private void cmd_yesPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_yesPaymentActionPerformed
        // TODO add your handling code here:
        String Amount,TexiNo;
          
            Amount = txt_payment.getText();
            TexiNo = txt_texiNo.getText();
        
        try {
            
            String sql1;
            Class.forName("com.mysql.jdbc.Driver");
            String host = "jdbc:mysql://localhost:3306/mysql";
            String uName = "root";
            String uPass = "maa";
            
            Connection con = DriverManager.getConnection(host,uName,uPass);
            Statement stmt = con.createStatement();
            
            sql1="update payment_tms set amount = "+Amount+" where texi_No = "+TexiNo+" and id = "+user_id+"";
            int rows1 = stmt.executeUpdate(sql1);
            
                Component frame = null ;
                if(rows1 >0){
                    JOptionPane.showMessageDialog(frame,"Your Texi booking Completed Successfully!!!!");
                }
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cmd_yesPaymentActionPerformed

    private void cmd_noPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_noPaymentActionPerformed
        // TODO add your handling code here:
        jp_booking.setVisible(false);
        jp_paying.setVisible(false);
        jp_cancel.setVisible(false);
        jp_txt.setVisible(true);
        
    }//GEN-LAST:event_cmd_noPaymentActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneActionPerformed

    private void txt_purposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_purposeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_purposeActionPerformed

    private void box_paymentModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_paymentModeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_box_paymentModeActionPerformed

    private void lbl_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cancelMouseClicked
        // TODO add your handling code here:
        jp_booking.setVisible(false);
        jp_paying.setVisible(false);
        jp_cancel.setVisible(true);
        jp_txt.setVisible(false);
    }//GEN-LAST:event_lbl_cancelMouseClicked

    private void txt_texiNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_texiNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_texiNumberActionPerformed

    private void cmd_noCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_noCancelActionPerformed
        // TODO add your handling code here:
        jp_booking.setVisible(false);
        jp_paying.setVisible(false);
        jp_cancel.setVisible(false);
        jp_txt.setVisible(true);
    }//GEN-LAST:event_cmd_noCancelActionPerformed

    private void cmd_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_logoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_page().setVisible(true);
            }
        });
    }//GEN-LAST:event_cmd_logoutActionPerformed

    private void cmd_doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_doneActionPerformed
        // TODO add your handling code here:
        String Name,Phone,Purpose,Address;
        
        Name = txt_name.getText();
        Phone = txt_phone.getText();
        Purpose = txt_purpose.getText();
        Address = txt_address.getText();
        
        try {
            String sql1,sql2;
            
            Class.forName("com.mysql.jdbc.Driver");
            String host = "jdbc:mysql://localhost:3306/mysql";
            String uName = "root";
            String uPass = "maa";
            
            Connection con = DriverManager.getConnection(host,uName,uPass);
            Statement stmt = con.createStatement();
            
            sql1 = "insert into bookin_tms(id,name,phone,purpose,address) "
                    + "values('"+user_id+"','"+Name+"','"+Phone+"','"+Purpose+"','"+Address+"')";
            int rows = stmt.executeUpdate(sql1);
           int rand = (new Random().nextInt(9999-1000)+1000) ;
           texi_no=rand;
           System.out.println("Texi No."+rand);
           int Amount = 0;
           
           sql2 = "insert into payment_tms(id,texi_No,amount) values('"+user_id+"','"+texi_no+"','"+Amount+"')";
           int rows2 = stmt.executeUpdate(sql2);
           Component frame = null ;
                if(rows2 >0){
                    JOptionPane.showMessageDialog(frame,"Now Go For Payment!!!!");
                }
        }
         catch (ClassNotFoundException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cmd_doneActionPerformed

    private void txt_texiNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_texiNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_texiNoActionPerformed

    private void cmd_yesCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_yesCancelActionPerformed
        // TODO add your handling code here:
        String Texi_No;
        
        Texi_No = txt_texiNumber.getText();
        try {
            String sql4;
            
            Class.forName("com.mysql.jdbc.Driver");
            String host = "jdbc:mysql://localhost:3306/mysql";
            String uName = "root";
            String uPass = "maa";
            
            Connection con = DriverManager.getConnection(host,uName,uPass);
            Statement stmt = con.createStatement();
            
            System.out.println("Texi No.:"+Texi_No);
            System.out.println("User_id:"+user_id);
            
            sql4 = "delete from payment_tms where texi_No = "+Texi_No+" and id="+user_id+"";
            int rows = stmt.executeUpdate(sql4);
            
             Component frame = null ;
                if(rows >0){
                    JOptionPane.showMessageDialog(frame,"Cancellation Completed Successfully!!!!");
                }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmd_yesCancelActionPerformed

    private void cmd_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_cancelActionPerformed
        // TODO add your handling code here:
        jp_booking.setVisible(false);
        jp_paying.setVisible(false);
        jp_cancel.setVisible(false);
        jp_txt.setVisible(true);
    }//GEN-LAST:event_cmd_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox box_paymentMode;
    private javax.swing.JButton cmd_cancel;
    private javax.swing.JButton cmd_done;
    private javax.swing.JButton cmd_logout;
    private javax.swing.JButton cmd_noCancel;
    private javax.swing.JButton cmd_noPayment;
    private javax.swing.JButton cmd_yesCancel;
    private javax.swing.JButton cmd_yesPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel jp_booking;
    private javax.swing.JPanel jp_cancel;
    private javax.swing.JPanel jp_paying;
    private javax.swing.JPanel jp_tms;
    private javax.swing.JPanel jp_txt;
    private javax.swing.JLabel lbl_booking;
    private javax.swing.JLabel lbl_cancel;
    private javax.swing.JLabel lbl_payment;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_payment;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_purpose;
    private javax.swing.JTextField txt_texiNo;
    private javax.swing.JTextField txt_texiNumber;
    // End of variables declaration//GEN-END:variables
}
